# PRanked - 4s Bot by syncwrld #
#       www.syncwrld.tech      #

# Para desenvolvedores #
debug: false

# ID do servidor do Discord #
guild-id: ''

# Configure o token do seu bot #
discord-bot-token: ''

# O canal do servidor em que os jogadores ficarão #
# esperando por uma partida #
wait-channel-id: ''

# Mensagem de status do bot #
bot-status-message: 'Esperando por uma nova partida!'